#!/bin/bash
# Script to generate a list of required GitHub secrets
# This helps you identify which secrets you need to configure

echo "=========================================="
echo "GitHub Secrets Required for Deployment"
echo "=========================================="
echo ""

echo "📋 REQUIRED SECRETS (Both Options):"
echo ""
echo "Application Secrets:"
echo "  - REACT_APP_MSAL_CLIENT_ID"
echo "  - REACT_APP_MSAL_TENANT_ID"
echo "  - REACT_APP_AZURE_CLIENT_ID"
echo "  - REACT_APP_AZURE_TENANT_ID"
echo "  - REACT_APP_REDIRECT_URI"
echo ""
echo "Docker Hub:"
echo "  - DOCKER_USERNAME"
echo "  - DOCKER_PASSWORD"
echo ""

echo "📋 ANSIBLE-SPECIFIC SECRETS (Option 1):"
echo ""
echo "Server Access:"
echo "  - ANSIBLE_HOST"
echo "  - ANSIBLE_USER"
echo "  - ANSIBLE_SSH_PRIVATE_KEY"
echo ""
echo "Deployment Configuration:"
echo "  - PRODUCTION_IP"
echo "  - PRODUCTION_DOMAIN"
echo "  - USE_IP (true/false)"
echo "  - USE_HTTPS (true/false)"
echo "  - LETSENCRYPT_EMAIL"
echo "  - K8S_NAMESPACE"
echo ""

echo "📋 KUBERNETES-SPECIFIC SECRETS (Option 2):"
echo ""
echo "Kubernetes Access:"
echo "  - KUBECONFIG"
echo "  - K8S_NAMESPACE"
echo ""
echo "Deployment Configuration:"
echo "  - PRODUCTION_DOMAIN"
echo ""

echo "📋 OPTIONAL SECRETS (Both Options):"
echo ""
echo "AWS S3 Logging:"
echo "  - REACT_APP_S3_BUCKET_NAME"
echo "  - REACT_APP_S3_REGION"
echo "  - REACT_APP_S3_ACCESS_KEY_ID"
echo "  - REACT_APP_S3_SECRET_ACCESS_KEY"
echo "  - AWS_ACCESS_KEY_ID"
echo "  - AWS_SECRET_ACCESS_KEY"
echo "  - AWS_REGION"
echo "  - S3_BUCKET_NAME"
echo ""
echo "Sentry Error Tracking:"
echo "  - REACT_APP_SENTRY_DSN"
echo "  - REACT_APP_SENTRY_ENVIRONMENT"
echo "  - REACT_APP_ENABLE_SENTRY"
echo "  - SENTRY_DSN"
echo ""
echo "Other Services:"
echo "  - REACT_APP_WORDPRESS_FEED_URL"
echo "  - REACT_APP_GOOGLE_CLIENT_ID"
echo ""

echo "=========================================="
echo "How to Add Secrets:"
echo "=========================================="
echo "1. Go to GitHub Repository"
echo "2. Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret'"
echo "4. Add each secret listed above"
echo ""
echo "For detailed instructions, see:"
echo ".github/DEPLOYMENT-GUIDE.md"
echo ""

